image: Visual Studio 2017

environment:
  matrix:
    - platform: x86
      python: Python37

    - platform: x64
      python: Python37-x64

install:
  - cmd: set PATH=C:\%python%;%PATH%
  - ps: (Get-Content .gitmodules | %{$_ -Replace "git@github.com:", "https://github.com/"}) | Out-File .gitmodules -Encoding ASCII
  - cmd: git submodule update --init --recursive
  - cmd: python -m pip install --upgrade pip setuptools wheel

build_script:
  - cmd: python setup.py bdist_wheel
  - ps: Invoke-Expression "python -m pip install $(Get-Childitem –Path dist -Include *.whl -File -Recurse)"
  - cmd: python -m pytest -x -s -v tests
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        Invoke-Expression "python -m pip install twine"
        Invoke-Expression "python -m twine upload --skip-existing dist/*.whl"
      }
