image: Visual Studio 2017

branches:
  only:
    - master
    - release

environment:
  CIBW_BUILD: cp37-*
  CIBW_TEST_REQUIRES: pytest
  CIBW_TEST_COMMAND: python -m pytest -x -s -v C:\projects\yapic-di\tests

install:
  - ps: (Get-Content .gitmodules | %{$_ -Replace "git@github.com:", "https://github.com/"}) | Out-File .gitmodules -Encoding ASCII
  - cmd: git submodule update --init --recursive
  - cmd: python -m pip install --upgrade cibuildwheel
  - cmd: touch .cibuildwheel

platform: [x64]

build_script:
  - ps: "Get-ChildItem Env:"
  - cmd: python -m cibuildwheel --output-dir wheelhouse
  - ps: >-
      if (($env:APPVEYOR_REPO_BRANCH -eq "release") -and ($env:APPVEYOR_REPO_TAG -eq "true")) {
        Invoke-Expression "python -m pip install twine"
        Invoke-Expression "python -m twine upload --skip-existing wheelhouse/*.whl"
      }

# artifacts:
#   - path: "wheelhouse\\*.whl"
#     name: Wheels
