env:
  global:
    - CIBW_BUILD="cp37-*"
    - CIBW_TEST_REQUIRES="pytest"
    - CIBW_TEST_COMMAND="pytest -x -s -v tests"

matrix:
  include:
    - language: python
      sudo: required
      python: "3.7"

install:
  - pip3 install --upgrade cibuildwheel

script:
  - cibuildwheel --output-dir wheelhouse
# branches:
#   only:
#     - prepare
#     - release
