matrix:
  include:
    - language: python
      dist: xenial
      sudo: required
      python: "3.7"

git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - ls -la libs/yapic.core/src/yapic/core/include

install:
  - python3 -m pip install --upgrade pip setuptools pytest wheel

script:
  - rm -rf pytest.py
  - python3 setup.py sdist

  # test sdis
  - cd dist
  - tar xvzf yapic*.tar.gz
  - cd "$(ls -d */ | grep yapic)"
  - python3 setup.py bdist_wheel

  - python3 -m pip install --upgrade dist/*.whl
  - python3 -m pytest -x -s -v ../../tests/
  - >-
    if [ "${TRAVIS_TAG:-}" != "" ]; then
      python3 -m pip install twine;
      python3 -m twine upload --skip-existing dist/*.tar.gz;
    fi
