matrix:
  include:
    - language: python
      dist: xenial
      sudo: required
      python: "3.7"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - CC="gcc-7"
        - CXX="g++-7"

git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

install:
  - python3 -m pip install --upgrade pip setuptools wheel pytest

script:
  - rm -rf pytest.py
  - python3 setup.py bdist_wheel
  - python3 -m pip install --upgrade dist/*.whl
  - python3 -m pytest -x -s -v tests
  # - >-
  #   if [ "${TRAVIS_TAG:-}" != "" ]; then
  #     python3 -m pip install twine;
  #     python3 -m twine upload --skip-existing dist/*.whl;
  #   fi
