version: 2

jobs:
  build:
    docker:
      - image: quay.io/pypa/manylinux1_x86_64

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: checkout submodules
          command: |
            sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
            git submodule update --init --recursive

      - run:
          name: init env
          command: |
            echo 'export PATH=/opt/python/cp37-cp37m/bin/:$PATH' >> $BASH_ENV

      - run:
          name: install dependencies
          command: |
            python3 -m pip install --upgrade pip setuptools pytest auditwheel

      - run:
          name: build
          command: |
            python3 setup.py bdist_wheel
            python3 -m auditwheel repair dist/*.whl

      - run:
          name: test
          command: |
            rm -rf pytest.py
            python3 -m pip install --upgrade wheelhouse/*.whl
            python3 -m pytest -x -s -v tests
