version: 2

_docker-x86-py37: &docker-x86-py37
  docker:
    - image: quay.io/pypa/manylinux1_i686
      environment:
        PYBIN: /opt/python/cp37-cp37m/bin/python3
  working_directory: ~/repo

_docker-x64-py37: &docker-x64-py37
  docker:
    - image: quay.io/pypa/manylinux1_x86_64
      environment:
        PYBIN: /opt/python/cp37-cp37m/bin/python3
  working_directory: ~/repo

_job: &job
  steps:
    - checkout

    - run:
        name: checkout submodules
        command: |
          sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
          git submodule update --init --recursive

    - run:
        name: install dependencies
        command: |
          "${PYBIN}" -m pip install --upgrade pip setuptools pytest auditwheel twine

    - run:
        name: build
        command: |
          "${PYBIN}" setup.py bdist_wheel
          "${PYBIN}" -m auditwheel repair dist/*.whl

    - run:
        name: test
        command: |
          rm -rf pytest.py
          "${PYBIN}" -m pip install --upgrade wheelhouse/*.whl
          "${PYBIN}" -m pytest -x -s -v tests

    - run:
        name: release
        command: |
          if [ "${CIRCLE_TAG:-}" != "" ]; then
            "${PYBIN}" -m twine upload --skip-existing wheelhouse/*.whl
          fi

jobs:
  x86-py37:
    <<: *docker-x86-py37
    <<: *job

  x64-py37:
    <<: *docker-x64-py37
    <<: *job

workflows:
  version: 2
  x86-py37: { jobs: [x86-py37] }
  x64-py37: { jobs: [x64-py37] }
