version: 2

executors:
  py37-x64:
    docker:
      - image: quay.io/pypa/manylinux1_x86_64
        environment:
          PYBIN: /opt/python/cp37-cp37m/bin/python3
    working_directory: ~/repo

  py37-x86:
    docker:
      - image: quay.io/pypa/manylinux1_i686
        environment:
          PYBIN: /opt/python/cp37-cp37m/bin/python3
    working_directory: ~/repo

_build-job: &build-job
  steps:
    - checkout

    - run:
        name: checkout submodules
        command: |
          sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
          git submodule update --init --recursive

    - run:
        name: install dependencies
        command: |
          "${PYBIN}" -m pip install --upgrade pip setuptools pytest auditwheel

    - run:
        name: build
        command: |
          "${PYBIN}" setup.py bdist_wheel
          "${PYBIN}" -m auditwheel repair dist/*.whl

    - persist_to_workspace:
        root: wheelhouse
        paths: "*.whl"

_test-job: &test-job
  steps:
    - checkout

    - attach_workspace:
        at: wheelhouse

    - run:
        name: test
        command: |
          rm -rf pytest.py
          "${PYBIN}" -m pip install --upgrade wheelhouse/*.whl
          "${PYBIN}" -m pytest -x -s -v tests

_release-job: &release-job
  filters:
    branch: { ignore: /.*/ }
    tags: { only: /^\d+\.\d+\.\d+$/ }
  steps:
    - run:
        name: release

jobs:
  build-x64:
    <<: *build-job
    executor: py37-x64

  test-x64:
    <<: *test-job
    executor: py37-x64

  release-x64:
    <<: *release-job
    executor: py37-x64

  build-x86:
    <<: *build-job
    executor: py37-x86

  test-x86:
    <<: *test-job
    executor: py37-x86

  release-x86:
    <<: *release-job
    executor: py37-x86

workflows:
  version: 2
  x86:
    jobs:
      - build-x86
      - test-x86: { requires: [build-x86] }
      - release-x86: { requires: [test-x86] }

  x64:
    jobs:
      - build-x64
      - test-x64: { requires: [build-x64] }
      - release-x64: { requires: [test-x64] }
