version: 2

jobs:
  build:
    docker:
      - image: quay.io/pypa/manylinux1_x86_64
        environment:
          PYBIN: /opt/python/cp37-cp37m/bin/python3

      - image: quay.io/pypa/manylinux1_i686
        environment:
          PYBIN: /opt/python/cp37-cp37m/bin/python3

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: checkout submodules
          command: |
            sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
            git submodule update --init --recursive

      - run:
          name: install dependencies
          command: |
            "${PYBIN}" -m pip install --upgrade pip setuptools pytest auditwheel

      - run:
          name: build
          command: |
            "${PYBIN}" setup.py bdist_wheel
            "${PYBIN}" -m auditwheel repair dist/*.whl

      - run:
          name: test
          command: |
            rm -rf pytest.py
            "${PYBIN}" -m pip install --upgrade wheelhouse/*.whl
            "${PYBIN}" -m pytest -x -s -v tests

      - run:
          name: release
          filters:
            branch: { ignore: /.*/ }
            tags: { only: /^\d+\.\d+\.\d+$/ }
          command: |
            echo "DO RELEASE"
